# Generated by Django 3.1.4 on 2021-04-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210408_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organizor',
            field=models.BooleanField(default=True),
        ),
    ]
